extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning
    allow-non-break-inline-imagel: true

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
